"""ini migration

Revision ID: 48094d4a3fa1
Revises: 
Create Date: 2025-01-21 19:08:28.479240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48094d4a3fa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('design',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('public_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_design')),
    sa.UniqueConstraint('public_url', name=op.f('uq_design_public_url'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('design')
    # ### end Alembic commands ###
