"""Change data column to JSON type

Revision ID: 523ca63e6afe
Revises: 48b213d03ad6
Create Date: 2024-12-23 17:16:17.145311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '523ca63e6afe'
down_revision = '48b213d03ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
         batch_op.execute('ALTER TABLE design ALTER COLUMN data TYPE JSON USING data::json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('design', schema=None) as batch_op:
      batch_op.execute('ALTER TABLE design ALTER COLUMN data TYPE TEXT')

    # ### end Alembic commands ###
